import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import SplashLayout from "./SplashLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Believe Fitness (Phong)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const fontClass = `${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`;

  return (
    <html lang="en">
      <body>
        <SplashLayout fontClass={fontClass}>
          {children}
        </SplashLayout>
      </body>
    </html>
  );
}
